# Generated by Django 3.1.2 on 2020-10-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_question'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
