# Generated by Django 3.1.2 on 2020-10-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201006_0836'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
